### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by daniel-j-h** [scanse/sweep-sdk#1]
Currently I only tested `libsweep`, `SweepPy` and `SweepJs` on my Linux Ubuntu machine.

For platform specifics we can dispatch in [config.mk](https://github.com/scanse/sweep-sdk/blob/f7fbfbd2e304887a23d13678b40e64ecff770485/libsweep/config.mk). I assume we have to change some specifics such as the installation paths, maybe some cflags/ldflags. The `_unix` implementations are POSIX-conforming and should Just Work (tm).

**Comment by daniel-j-h** [comment]
Here's a macOS build running on Windows: https://github.com/scanse/sweep-sdk/pull/29

Surprisingly enough it Just Works (tm). At least compiling and linking the dummy implementation.

The Sweep comes with a FTDI USB serial device converter which a friend of mine said should work just fine on macOS passing in a dev path such as `/dev/cu.usbserial0233`.

I can't test this and would love for someone on macOS to try it out with a real device.

**Comment by dcyoung** [comment]
I gave the travis-osx build a shot on OSX El Capitan. 

Obviously the hardcoded serial port name [here](https://github.com/scanse/sweep-sdk/blob/033d4a6166701cef4adb80161055d407a9a1cbf1/libsweep/src/sweep.cc#L52) had to be changed out in favor of the appropriate /dev/cu.* for the device. The only other issue I encountered was the baud rate. The get_baud function was falling through to the default error case [here](https://github.com/scanse/sweep-sdk/blob/033d4a6166701cef4adb80161055d407a9a1cbf1/libsweep/src/unix/serial.cc#L239), and B115200 wasn't identifiable when i tried it manually (ie: `speed_t baud = B115200;`). 

I just went ahead and hard coded the value by changing this line [here](https://github.com/scanse/sweep-sdk/blob/033d4a6166701cef4adb80161055d407a9a1cbf1/libsweep/src/unix/serial.cc#L320) to `speed_t baud = 115200;` and everything worked just fine. Library built and installed and the c and c++ examples ran as expected. I'll try to test the bindings now.

**Comment by daniel-j-h** [comment]
Sweet!

The dev path auto-detection was something we wanted to remove anyway.

The Node binding build system lacked support for macOS - I just added it in https://github.com/scanse/sweep-sdk/pull/29.

**Comment by daniel-j-h** [comment]
Is this still a priority? From reading the old comments above it seems like macOS support works more or less out of the box, with adaptions to the baudrate. @dcyoung should we try and get this into a proper release and tested, so that people can work with their Sweep - now that they're shipping - on macOS, too?
