### ISSUE TITLE
Which languages to support?

### ISSUE THREAD

**Issue by daniel-j-h** [scanse/sweep-sdk#11]
At the moment there is `libsweep` the low-level ABI and API stable C library. There is a convenient C++11 header on top of that, Python2/3 and NodeJS FFI bindings.

Which of those do we actually want to support? The beauty of having a ABI and API compatible library is that FFI bindings are very lean and elegant to write. The downside is, someone still has to build and maintain not only the abstractions needed for the bindings, but also e.g. the build system, how to package and ship bindings etc.

If we decided on languages to support, we need a plan for packing library + bindings up to make the user's life as easy as possible.

**Comment by daniel-j-h** [comment]
For inspiration: there is a JNI Java wrapper for parts of the API at
https://github.com/PeterJohnson/sweep-sdk

**Comment by daniel-j-h** [comment]
Closing as not actionable on our side. If users want other bindings they have to help out here.

**Comment by kenzierocks** [comment]
Would you be interested in a PR for Java bindings using JNA? I have it written out [here](https://github.com/Team5818/sweep-sdk/tree/feature/java-jna).

**Comment by daniel-j-h** [comment]
Yes sure, as long as you can invest the time to maintain it - because I think you'd be the main developer for the Java bindings then. I just had a look over your branch and it looks good very clean and good overall - there are some small things I'd like to see (such as Travis integration etc.) but it's probably better to just make a Pull Request and we can then talk about minor details there.

Pinging @zugaldia who can probably talk a bit about Java bindings and had the use-case for a Java SDK version for his Android Robocar project: https://github.com/zugaldia/android-robocar/issues/9.

**Comment by zugaldia** [comment]
@kenzierocks I've done some JNI work before using [a library we built in-house](https://github.com/mapbox/jni.hpp). Though I'm not super familiar with JNA, this is a great option too!

I'd love to see Java bindings for this project, if you all decide to open a PR I'll be happy to help with the review. Eventually, I'd bring it to https://github.com/zugaldia/android-robocar/issues/9 for some "real world" usage.

**Comment by daniel-j-h** [comment]
@kenzierocks want to open a pull request with your bindings? :)

**Comment by kenzierocks** [comment]
Apologies, @daniel-j-h -- I was busy with school and forgot about this. PR created at #83!

**Comment by daniel-j-h** [comment]
Hey, nothing to apologize for! I just wanted to ping and see how things are going :) Thanks for the PR!
