### ISSUE TITLE
What layer could we introduce an IP socket transport?

### ISSUE THREAD

**Issue by kent-williams** [scanse/sweep-sdk#13]
Several applications are going to require communicating with sweep over IP. What layer of the SDK would be most appropriate to introduce this functionality?

**Comment by daniel-j-h** [comment]
In https://github.com/scanse/sweep-sdk/issues/47 I added an example using ZeroMQ and Protobuf for a pub/sub setup. Is this good enough or should we bring this out of the examples and into the main `libsweep` project?

What are the requirements here, what do we actually need?

**Comment by daniel-j-h** [comment]
Closing as not actionable on our side. Examples are there, we could install the publisher and subscriber, in addition to the proto scheme if needs be.
