### ISSUE TITLE
Motor Speed commands

### ISSUE THREAD

**Issue by kent-williams** [scanse/sweep-sdk#14]
@daniel-j-h  I noticed that you still have MA and MX in the protocol. Instead of having a separate command for start, stop, and adjusting speed, we decided to just use MS and have 00 be motor stop and anything positive start the motor. 

I'll work on getting the protocol spec in this repo soon.

**Comment by daniel-j-h** [comment]
Where do you see it in the protocol? I changed it last week after you told me about it

https://github.com/scanse/sweep-sdk/blob/853f113543621daf6ce8553177f7d2153d2657c4/libsweep/protocol.h#L20-L21

and this is the implementation:

https://github.com/scanse/sweep-sdk/blob/853f113543621daf6ce8553177f7d2153d2657c4/libsweep/sweep.c#L295-L321

Agreed - it would be great to have to specification as a plaintext / markdown file in this repository.

**Comment by kent-williams** [comment]
I must have looked at an old commit, it was referenced in an issue about the interface. Thanks for clearing that up.
