### ISSUE TITLE
Travis CI Integration

### ISSUE THREAD

**Issue by daniel-j-h** [scanse/sweep-sdk#2]
Similar to the [.travis.yml here](https://github.com/scanse/sweep-sdk-cpp/blob/e74780f92d0b195d00aff24c342dc519c19e82da/.travis.yml) we want CI integration.

Compiling `libsweep` is be a good start, properly testing all sub-projects would be even better.

Tasks:

- [x] enable Travis for this repository
- [x] add a .travis.yml config
- [x] compile `libsweep.so`
- [x] build dummy `libsweep.so` (`make dummy`) and test projects against

**Comment by kent-williams** [comment]
repo public

travis enabled
