### ISSUE TITLE
Quickstart docs for the examples missing a command

### ISSUE THREAD

**Issue by dcyoung** [scanse/sweep-sdk#24]
I was following along with the quickstart guide, as I'm sure most users will do:
https://github.com/scanse/sweep-sdk/blob/a33032a5626d43e1d72b3457dda8f6ebb6bc86ca/libsweep/examples/README.md

The `cmake ..` command in the following docs will error.
```bash
mkdir build
cmake ..
cmake --build .
```
I believe it should be changed to... 
```bash
mkdir build
cd build
cmake ..
cmake --build .
```

**Comment by daniel-j-h** [comment]
Yes, cmake needs to be called from the build dir (out-of-source build).
