### ISSUE TITLE
sweep-ctl: interacting with the device from the command line

### ISSUE THREAD

**Issue by daniel-j-h** [scanse/sweep-sdk#49]
We really should have some sort of `sweep-ctl` binary to get set and reset the device state.

With an interface similar to

```
$ sweep-ctl /dev/ttyUSB0 get motor_speed
3
$ sweep-ctl /dev/ttyUSB0 set motor_speed 5
5
$ sweep-ctl /dev/ttyUSB0 set motor_speed
3
```

Otherwise users have to modify the examples and build their own binaries for these kind of interactions.

Should get installed in combination with a man page (generated by pandoc).

**Comment by kent-williams** [comment]
Great idea @daniel-j-h! 
This is certainly preferable to hassling with command line serial commands.
