### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by daniel-j-h** [scanse/sweep-sdk#5]
I can't help you much there. If we want this, we have to adapt the build system (config.mk, Makefile for `libsweep`, maybe gyp for SweepJs). Then provide implementations along the `_unix` ones conforming to our interfaces.

**Comment by MikeGitb** [comment]
I would be willing to give it a try, if someone with a windows machine could test it. It seems as if I have to wait another 1-2 Month until I get my device :(

**Comment by dcyoung** [comment]
@MikeGitb  The `win-support` branch now works, but only with MinGW.

We should look into Visual Studio compatibility as well, as this may be requested by windows users. 

@daniel-j-h do you want me to form a pull request for the win-support branch. Its got a few other changes that we might want to throw in before diving into the C++ conversion.

- updated config and Makefile
- updated file structure (src/inc/obj/bin directories)
- temporary patch for the scan throughput, until threads + queue replace the current implementation

It will need a once over to double check formatting and documentation but it builds just fine on my windows MinGW, my ubuntu and the travis builds.

**Comment by daniel-j-h** [comment]
Can you split off unrelated changes.

Windows compilation should only have to touch `config.mk`, `Makefile`, and the platform specific implementations, right?

Maybe let's merge the C++ implementation pull request first, then you can use chrono and thread already. But this should be a different pull request.

**Comment by dcyoung** [comment]
There are a few things that could be split off. 

The temporary patch to the `get_scan` function can certainly be moved to its own pull request.... or just ignored until the thread worker replaces it. 

In theory the win-support should only touch `config.mk` and `Makefile`, but there were a few exceptions. For example the addition of the time_win was restricted to milliseconds, so I had to also change the time_unix to keep a consistent abstraction. As you mentioned, this won't matter when its all replaced by chrono and thread.

However, changes to the makefile/config.mk for both the new file structure and the windows support are currently interconnected. I could probably redo them as two separate pull requests... but is there a preferable order?

The port name is different on windows/unix, so we'll have to rework the way the simple constructor and the examples work.  Perhaps providing a port name as an argument to the examples. 

I'm also not sure how to specify that building the viewer example should be conditional on having SFML... currently i just commented out the viewer related elements in the CMakeLists file.

In general, what order would make the most sense... I was thinking something like:

- Merge Signal Strength format PR
- Create and merge PR for file structure changes
- Merge C++ PR
- Create and merge PR for a more specific win-support branch stripped of unrelated changes
- Implement C++ conversion
- Add C++ thread worker

**Comment by daniel-j-h** [comment]
Update: work on this is happening in https://github.com/scanse/sweep-sdk/pull/44.

**Comment by daniel-j-h** [comment]
This landed with https://github.com/scanse/sweep-sdk/pull/44.
