### ISSUE TITLE
Check for !device.is_scanning before sending commands

### ISSUE THREAD

**Issue by dcyoung** [scanse/sweep-sdk#56]
It looks like the sample rate commit broke the c++ example by placing the calls to get_motor_speed and get_sample_rate AFTER `start_scanning`...

https://github.com/scanse/sweep-sdk/blob/4c12c07c16c6fc82f49fed78929119f1db1e1b07/libsweep/examples/example.cc#L11

This probably works with the dummy library because it sends back information regardless of whether or not its scanning. However, the actual sweep device cannot receive or respond to commands other than `DX\n` while it is scanning. The calls to `get_motor_speed` and `get_sample_rate` need to be placed before `start_scanning`. 

Additionally, in those functions we should probably check if the device is scanning and simply error or report it somehow before trying to message a device... which will only cause more errors. We can do this easily, as we already set a `is_scanning` bool in the `sweep_device` struct

**Comment by MikeGitb** [comment]
I don't have a strong feeling either way, but how about starting to scan automatically?

**Comment by daniel-j-h** [comment]
Hm. I followed the initial design and giving that the library is quite low-level having start and stop functions on the device seemed like a good idea. I can see how the constructor should start and the destructor should stop, making use of the device's lifetime.

**Comment by MikeGitb** [comment]
I meant Autostartimg when getScan is called.

**Comment by dcyoung** [comment]
Hmmm. I think there is some confusion here. The device should definitely be created without auto starting the scanning process. ie: we should be able to explicitly start and stop the scanning as we currently do. 

The only issue is that the C++ example sends two other commands (get_motor_speed, and get_sample_rate) AFTER the scanning is started. When designing a user application, one should never send a command other than STOP to the device while it is scanning. However, since it is possible to explicitly call the functions when the device is scanning, we are seeing errors (likely originating in the read function timing out because the device never responded). 

We should prevent this case by never allowing the command to be sent if the device is scanning. Ie: in `get_motor_speed` and all other functions that send commands (other than stop_scanning), we should check that the device is NOT scanning before sending a command.

**Comment by dcyoung** [comment]
I went ahead and pushed the example-c++ fix... but I'm leaving this open and changing the title for discussion regarding the addition of checks for `is_scanning` in all functions that send commands.

**Comment by daniel-j-h** [comment]
Agree. We have to assert the device not scanning for those functions as a precondition. For dummy and real library. And make it clear in docs.

**Comment by dcyoung** [comment]
Sorry, accidentally closed and reopened the issue. 

@daniel-j-h  PR is up at #57, go ahead and merge if all looks good.

**Comment by MikeGitb** [comment]
If the device doesn'T accept any commands while in scanning mode then what happens, if the program gets terminated or simply doesn't stop the device at the end and on the next program start, the device is already scanning? Maybe the API should always send a stop command first. I think an assert is counterproductive here.

**Comment by daniel-j-h** [comment]
We already do that see [here](https://github.com/scanse/sweep-sdk/blob/334f74aab5eb716c17c466cb2718920ed1d88f09/libsweep/src/sweep.cc#L72).

That's the reason the `stop_scanning` does not assert for `is_scanning`.

It may seem like a workaround but with a stateful hardware device there is only so much we can do.

**Comment by dcyoung** [comment]
I believe the current firmware also supports the reset command while the device is scanning. We are debating whether or not to support this, or assume that anytime a user will reset a device, they can explicitly check and call stop scanning.
