### ISSUE TITLE
Scan Response Checksum Depends on Endianess

### ISSUE THREAD

**Issue by daniel-j-h** [scanse/sweep-sdk#8]
For the scan respone packet's checksum the spec. says:

> adding the six bytes of data

isn't this endianness-dependant for the two-byte `uint16_t` types? That is, the current way of sliding over the chunk of memory is little-endian specific. Should this at least be documented in the spec?

[Relevant location](https://github.com/scanse/sweep-sdk/blob/f7fbfbd2e304887a23d13678b40e64ecff770485/libsweep/protocol.h#L120-L129)

**Comment by dcyoung** [comment]
The byte order should be irrelevant given that we are adding the six bytes individually. That is to say, when performing the checksum, the azimuth pair or distance pair are not added to a growing sum as a `uint16_t`, but rather the individual bytes of each pair are added as `uint8_t`. Check out this article for more info:
https://support.scanse.io/hc/en-us/articles/115001403947-Parsing-Sensor-Reading-Data
